trustDomain: ${SPIFFE_TRUST_DOMAIN}
spireServerSocket: ${SPIRE_SERVER_SOCKET}
interval: "${SLURM_SYNCER_INTERVAL}"
className: "${SLURM_SYNCER_CLASS_NAME}"
metricsAddr: "${SLURM_SYNCER_METRICS_ADDR}"
parentIDTemplate: "${SLURM_SYNCER_PARENT_ID_TEMPLATE}"
spiffeIDTemplate: "${SLURM_SYNCER_SPIFFE_ID_TEMPLATE}"
